<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbdd38e61fbda382c984b96a4aadfe7d2
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Plummer\\Calendarful\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Plummer\\Calendarful\\' => 
        array (
            0 => __DIR__ . '/..' . '/plummer/calendarful/src',
            1 => __DIR__ . '/..' . '/plummer/calendarful/tests',
        ),
    );

    public static $classMap = array (
        'ExpressiveDate' => __DIR__ . '/..' . '/jasonlewis/expressive-date/src/ExpressiveDate.php',
        'ExpressiveDateServiceProvider' => __DIR__ . '/..' . '/jasonlewis/expressive-date/src/ExpressiveDateServiceProvider.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbdd38e61fbda382c984b96a4aadfe7d2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbdd38e61fbda382c984b96a4aadfe7d2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbdd38e61fbda382c984b96a4aadfe7d2::$classMap;

        }, null, ClassLoader::class);
    }
}
